"""Initial migration

Revision ID: c18a4a953b17
Revises: 
Create Date: 2021-04-21 16:02:07.862188

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c18a4a953b17"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "person",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slack_user_id", sa.String(length=16), nullable=True),
        sa.Column("ghost_user_id", sa.String(length=16), nullable=True),
        sa.Column("first_name", sa.String(length=32), nullable=False),
        sa.Column("last_name", sa.String(length=32), nullable=True),
        sa.Column("display_name", sa.String(length=80), nullable=True),
        sa.CheckConstraint("COALESCE(slack_user_id, ghost_user_id, display_name) IS NOT NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("person", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_person_ghost_user_id"), ["ghost_user_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_person_slack_user_id"), ["slack_user_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_person_display_name"), ["display_name"], unique=False)

    op.create_table(
        "quote",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["person.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("quote")
    with op.batch_alter_table("person", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_person_slack_user_id"))
        batch_op.drop_index(batch_op.f("ix_person_ghost_user_id"))
        batch_op.drop_index(batch_op.f("ix_person_display_name"))

    op.drop_table("person")
    # ### end Alembic commands ###
